-- tabla.
CREATE TABLE PRODUCTOS_XML (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CATEGORIA VARCHAR2(100),
    PRECIO NUMBER(12,2),
    STOCK NUMBER
);

COMMIT;

-- verificar la tabla.
DESC PRODUCTOS_XML;

-- antes de realizar una nueva prueba.
DELETE FROM PRODUCTOS_XML;

COMMIT;